services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: follow-new-vpn-vhq-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    command: ["python", "main.py"]
